import type { ContentEntry } from './types'

export const BUILDER_ENTRIES: ContentEntry[] = [
  { key: 'builder.hero.title', value: { en: "Describe the agent. I'll build it.", ko: '에이전트를 설명해 주세요. 제가 만들게요.' }, context: 'Serif hero in the Build panel before a session starts.', surface: 'builder', kind: 'title' },
  { key: 'builder.hero.sub', value: { en: 'Tell me who it serves and what it should get done — the configuration fills in live as we go.', ko: '누구를 상대하고 무엇을 해내야 하는지 알려주세요 — 대화하는 동안 구성이 실시간으로 채워집니다.' }, context: 'De-voiced on purpose: the build experience is chat-first; voice is optional.', surface: 'builder', kind: 'hint' },
  { key: 'builder.hero.composer.placeholder', value: { en: 'Describe the agent you need…', ko: '필요한 에이전트를 설명하세요…' }, context: 'Hero composer in the Build dock — typing starts a TEXT session (no mic prompt).', surface: 'builder', kind: 'placeholder' },
  { key: 'builder.intake.intro.title', value: { en: "Let's start with your business", ko: '비즈니스부터 알려주세요' }, context: 'Step 1 — the ONE primary action is handing over material (site/doc); guided questions are the fallback. Keep it about the user\'s business + who calls them.', surface: 'builder', kind: 'title' },
  { key: 'builder.intake.intro.sub', value: { en: "Share your site or a doc and I'll learn who your callers are and what they need.", ko: '사이트나 자료를 주시면 콜러가 누구이고 무엇이 필요한지 파악합니다.' }, surface: 'builder', kind: 'hint' },
  { key: 'builder.intake.intro.no-material', value: { en: "No site or doc? Answer a few questions", ko: '사이트·자료가 없나요? 몇 가지 질문에 답하기' }, context: 'Fallback link from step 1 into the guided industry → use-case questions.', surface: 'builder', kind: 'cta' },
  { key: 'builder.intake.intro.reading-note', value: { en: "Reading your business so I can fill in the prompt, knowledge, and test callers — not just the use case.", ko: '프롬프트·지식·테스트 콜러까지 채우기 위해 비즈니스를 읽는 중입니다 — 용도만이 아니라요.' }, context: 'Shown while the hero reads site/doc — frames the read as feeding the whole configuration, not only intent.', surface: 'builder', kind: 'status' },
  { key: 'builder.intake.industry.title', value: { en: 'Who calls this agent?', ko: '누가 이 에이전트에게 전화하나요?' }, context: 'Fallback step (only when no material) — industries framed as the people who call. Mirrors cartesia.ai verticals underneath.', surface: 'builder', kind: 'title' },
  { key: 'builder.intake.industry.sub', value: { en: "Pick the closest — I'll ask the right follow-ups.", ko: '가장 가까운 것을 고르면 맞는 질문을 이어갑니다.' }, surface: 'builder', kind: 'hint' },
  { key: 'builder.intake.usecase.title', value: { en: 'What do they call about?', ko: '무엇 때문에 전화하나요?' }, context: 'Fallback step 2 — what callers need, per industry.', surface: 'builder', kind: 'title' },
  { key: 'builder.intake.usecase.read-sub', value: { en: 'Got it — {name}. What do they call about?', ko: '확인했어요 — {name}. 무엇 때문에 전화하나요?' }, context: 'Use-case subhead AFTER reading material — reflects the business name back to prove the read happened.', surface: 'builder', kind: 'hint' },
  { key: 'builder.intake.back', value: { en: 'Back', ko: '뒤로' }, surface: 'builder', kind: 'cta' },
  { key: 'builder.intake.industry.finance', value: { en: 'Financial services', ko: '금융 서비스' }, surface: 'builder', kind: 'label' },
  { key: 'builder.intake.industry.finance.sub', value: { en: 'Fraud checks, support, collections, accounts', ko: '사기 확인 · 고객 지원 · 추심 · 계좌' }, surface: 'builder', kind: 'hint' },
  { key: 'builder.intake.industry.healthcare', value: { en: 'Healthcare', ko: '헬스케어' }, surface: 'builder', kind: 'label' },
  { key: 'builder.intake.industry.healthcare.sub', value: { en: 'Scheduling, refills, intake, billing', ko: '예약 · 처방 리필 · 접수 · 청구' }, surface: 'builder', kind: 'hint' },
  { key: 'builder.intake.industry.government', value: { en: 'Government & public sector', ko: '정부 · 공공' }, surface: 'builder', kind: 'label' },
  { key: 'builder.intake.industry.government.sub', value: { en: 'Citizen services, benefits, permits', ko: '민원 · 복지 · 인허가' }, surface: 'builder', kind: 'hint' },
  { key: 'builder.intake.industry.other', value: { en: 'Something else', ko: '기타 업종' }, surface: 'builder', kind: 'label' },
  { key: 'builder.intake.industry.other.sub', value: { en: 'Any other business', ko: '그 외 모든 비즈니스' }, surface: 'builder', kind: 'hint' },
  { key: 'builder.intake.usecase.finance.fraud', value: { en: 'Fraud & verification calls', ko: '사기 탐지 · 본인 확인' }, surface: 'builder', kind: 'label' },
  { key: 'builder.intake.usecase.finance.support', value: { en: 'Customer support', ko: '고객 지원' }, surface: 'builder', kind: 'label' },
  { key: 'builder.intake.usecase.finance.collections', value: { en: 'Collections & reminders', ko: '추심 · 납부 안내' }, surface: 'builder', kind: 'label' },
  { key: 'builder.intake.usecase.finance.account', value: { en: 'Account opening', ko: '계좌 개설' }, surface: 'builder', kind: 'label' },
  { key: 'builder.intake.usecase.finance.loan', value: { en: 'Loan assistance', ko: '대출 안내' }, surface: 'builder', kind: 'label' },
  { key: 'builder.intake.usecase.healthcare.scheduling', value: { en: 'Appointment scheduling', ko: '예약 관리' }, surface: 'builder', kind: 'label' },
  { key: 'builder.intake.usecase.healthcare.refills', value: { en: 'Prescription refills', ko: '처방 리필' }, surface: 'builder', kind: 'label' },
  { key: 'builder.intake.usecase.healthcare.intake', value: { en: 'Patient intake', ko: '환자 접수' }, surface: 'builder', kind: 'label' },
  { key: 'builder.intake.usecase.healthcare.billing', value: { en: 'Billing & benefits', ko: '청구 · 보험 확인' }, surface: 'builder', kind: 'label' },
  { key: 'builder.intake.usecase.healthcare.afterhours', value: { en: 'After-hours answering', ko: '야간 응대' }, surface: 'builder', kind: 'label' },
  { key: 'builder.intake.usecase.government.citizen', value: { en: 'Citizen services line', ko: '민원 응대' }, surface: 'builder', kind: 'label' },
  { key: 'builder.intake.usecase.government.benefits', value: { en: 'Benefits & eligibility', ko: '복지 · 자격 문의' }, surface: 'builder', kind: 'label' },
  { key: 'builder.intake.usecase.government.permits', value: { en: 'Appointments & permits', ko: '방문 예약 · 인허가' }, surface: 'builder', kind: 'label' },
  { key: 'builder.intake.usecase.government.forms', value: { en: 'Form assistance', ko: '서류 작성 지원' }, surface: 'builder', kind: 'label' },
  { key: 'builder.intake.usecase.generic.support', value: { en: 'Customer support', ko: '고객 지원' }, surface: 'builder', kind: 'label' },
  { key: 'builder.intake.usecase.generic.scheduling', value: { en: 'Appointment scheduling', ko: '예약 관리' }, surface: 'builder', kind: 'label' },
  { key: 'builder.intake.usecase.generic.sales', value: { en: 'Sales follow-up', ko: '세일즈 팔로업' }, surface: 'builder', kind: 'label' },
  { key: 'builder.intake.usecase.generic.survey', value: { en: 'Customer survey', ko: '고객 설문' }, surface: 'builder', kind: 'label' },
  { key: 'builder.intake.materials.url.placeholder', value: { en: 'yourbusiness.com', ko: '회사 웹사이트 주소' }, context: 'Website input on step 1 (intro).', surface: 'builder', kind: 'placeholder' },
  { key: 'builder.intake.usecase.other', value: { en: 'Something else', ko: '다른 업무' }, context: 'Dashed last row of every use-case list — starts the chat with just the industry named.', surface: 'builder', kind: 'cta' },
  { key: 'builder.hero.title.edit', value: { en: 'What should change?', ko: '무엇을 바꿀까요?' }, context: 'Hero title when the Build dock opens on an EXISTING agent (edit mode).', surface: 'builder', kind: 'title' },
  { key: 'builder.hero.sub.edit', value: { en: "Describe the change and I'll patch just that — config, voice, knowledge, or flow.", ko: '바꿀 내용을 말하면 그 부분만 수정합니다 — 구성, 보이스, 지식, 플로우.' }, surface: 'builder', kind: 'hint' },
  { key: 'builder.hero.composer.placeholder.edit', value: { en: 'Describe the change…', ko: '바꿀 내용을 입력하세요…' }, context: 'Hero composer placeholder in EDIT mode (existing agent loaded).', surface: 'builder', kind: 'placeholder' },
  { key: 'builder.hero.composer.placeholder.url', value: { en: 'Paste your website URL…', ko: '웹사이트 URL을 붙여넣으세요…' }, context: 'Composer placeholder after tapping "Start from your website".', surface: 'builder', kind: 'placeholder' },
  { key: 'builder.hero.action.website', value: { en: 'Start from your website', ko: '웹사이트로 시작' }, context: 'Hero action — I read the site and draft a grounded agent.', surface: 'builder', kind: 'cta' },
  { key: 'builder.hero.action.doc', value: { en: 'Import a doc', ko: '문서 가져오기' }, context: 'Hero action — .txt/.md upload, starts a text session and files facts into the KB.', surface: 'builder', kind: 'cta' },
  { key: 'builder.hero.seed.receptionist', value: { en: 'Appointment receptionist', ko: '예약 접수원' }, context: 'Example chip — pre-fills the composer, does not auto-send.', surface: 'builder', kind: 'cta' },
  { key: 'builder.hero.seed.support', value: { en: 'Customer support line', ko: '고객 지원 라인' }, surface: 'builder', kind: 'cta' },
  { key: 'builder.hero.seed.survey', value: { en: 'Feedback survey caller', ko: '만족도 조사 콜러' }, surface: 'builder', kind: 'cta' },
  { key: 'builder.hero.seed.edit-voice', value: { en: 'Change the voice', ko: '보이스 변경' }, context: 'Edit-mode example chip.', surface: 'builder', kind: 'cta' },
  { key: 'builder.hero.seed.edit-hours', value: { en: 'Update business hours', ko: '영업시간 수정' }, surface: 'builder', kind: 'cta' },
  { key: 'builder.hero.seed.edit-escalation', value: { en: 'Add an escalation path', ko: '에스컬레이션 추가' }, surface: 'builder', kind: 'cta' },
  { key: 'builder.hero.talk', value: { en: 'Or talk it through', ko: '음성으로 진행하기' }, context: 'Secondary entry under the hero composer — starts a VOICE session.', surface: 'builder', kind: 'cta' },
  { key: 'builder.hero.connecting', value: { en: 'Connecting…', ko: '연결 중…' }, surface: 'builder', kind: 'status' },
  { key: 'builder.hero.retry', value: { en: 'Try again', ko: '다시 시도' }, surface: 'builder', kind: 'cta' },
  { key: 'builder.caption.stack', value: { en: 'Ears Ink-2 · Voice Sonic-3 · Reasoning Claude' }, context: 'Model-stack credit line. Brand/product names — left untranslated by design.', surface: 'builder', kind: 'hint' },
  { key: 'builder.turn.listening', value: { en: 'Listening', ko: '듣는 중' }, surface: 'builder', kind: 'status' },
  { key: 'builder.turn.your-turn', value: { en: 'Your turn', ko: '내 차례' }, context: 'Listening-state label in a TEXT session (mic is off — "Listening" would mislead).', surface: 'builder', kind: 'status' },
  { key: 'builder.turn.thinking', value: { en: 'Thinking…', ko: '생각 중…' }, surface: 'builder', kind: 'status' },
  { key: 'builder.turn.speaking', value: { en: 'Speaking', ko: '말하는 중' }, surface: 'builder', kind: 'status' },
  { key: 'builder.role.you', value: { en: 'You', ko: '나' }, context: 'Transcript speaker label.', surface: 'builder', kind: 'label' },
  { key: 'builder.role.builder', value: { en: 'Builder', ko: '빌더' }, surface: 'builder', kind: 'label' },
  { key: 'builder.composer.placeholder.listening', value: { en: 'Speak, or type here…', ko: '말하거나 입력하세요…' }, surface: 'builder', kind: 'placeholder' },
  { key: 'builder.composer.placeholder.wait', value: { en: 'Wait for your turn…', ko: '차례를 기다려 주세요…' }, surface: 'builder', kind: 'placeholder' },
  { key: 'builder.composer.placeholder.text', value: { en: 'Type a message…', ko: '메시지를 입력하세요…' }, context: 'Composer placeholder in a TEXT session — no mic, so no "speak" invitation.', surface: 'builder', kind: 'placeholder' },
  { key: 'builder.end', value: { en: 'End', ko: '종료' }, context: 'Quiet text button that ends the builder session.', surface: 'builder', kind: 'cta' },
  { key: 'builder.voice.enable', value: { en: 'Switch to voice', ko: '음성으로 전환' }, context: 'Status-row button in a TEXT session — upgrades it to voice in place (TTS + mic), conversation intact.', surface: 'builder', kind: 'cta' },
  { key: 'builder.mic-unavailable', value: { en: 'Type instead', ko: '입력으로 대체' }, context: 'Shown with a mic-off icon when getUserMedia was denied.', surface: 'builder', kind: 'status' },
  { key: 'builder.done-badge', value: { en: 'Config complete', ko: '구성 완료' }, surface: 'builder', kind: 'badge' },
  { key: 'builder.attach.title', value: { en: 'Give the builder your material', ko: '빌더에게 자료를 주세요' }, context: 'Paperclip popover heading.', surface: 'builder', kind: 'title' },
  { key: 'builder.attach.url.placeholder', value: { en: 'yourbusiness.com' }, context: 'Example domain — kept ASCII in all locales.', surface: 'builder', kind: 'placeholder' },
  { key: 'builder.attach.url.cta', value: { en: 'Read', ko: '읽기' }, surface: 'builder', kind: 'cta' },
  { key: 'builder.attach.files.cta', value: { en: 'Upload .txt / .md files', ko: '.txt / .md 파일 업로드' }, surface: 'builder', kind: 'cta' },
  { key: 'builder.attach.reading', value: { en: 'Reading {source}…', ko: '{source} 읽는 중…' }, surface: 'builder', kind: 'status' },
  { key: 'builder.attach.context-chip', value: { en: 'Business context — {source}', ko: '비즈니스 컨텍스트 — {source}' }, context: 'Compact attachment chip shown in place of the full material brief in the transcript (the LLM still receives the full text).', surface: 'builder', kind: 'label' },
  { key: 'builder.attach.summarizing', value: { en: 'Summarizing {source}…', ko: '{source} 요약 중…' }, context: 'Second ingest phase — haiku compresses the raw text into a brief.', surface: 'builder', kind: 'status' },
  { key: 'builder.thinking.drafting', value: { en: 'Drafting the agent — prompt, voice, greeting…', ko: '에이전트 초안 작성 중 — 프롬프트·보이스·인사말…' }, context: 'Thinking status for the FIRST brain turn (empty panel): it always produces a full draft.', surface: 'builder', kind: 'status' },
  { key: 'builder.thinking.updating', value: { en: 'Updating the draft…', ko: '초안 업데이트 중…' }, surface: 'builder', kind: 'status' },
  { key: 'builder.greeting', value: { en: "Hi — I design voice agents. Tell me who it'll talk to and what it should get done, and I'll draft it while we talk." }, context: 'SPOKEN via Sonic TTS and shown as the first transcript line. en-only until spoken-Korean is validated — falls back to en in ko locale.', surface: 'builder', kind: 'hint' },
  { key: 'builder.greeting.edit', value: { en: "I've loaded {name}. Tell me what you'd like to change — the prompt, voice, flow, or knowledge." }, context: 'Opening line when the Build tab opens on an EXISTING agent. Spoken via TTS; en-only like the creation greeting.', surface: 'builder', kind: 'hint' },
]
